import Head from "next/head";
import React from "react";
import AppHeader from "../components/AppHeader";

const BaseLayout = ({ children,pageTitle, ...props }) => {
  return (
    <div>
      {" "}
      <Head>
        <title>{pageTitle || "Next js beginner App"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader />
      <div>{children}</div>
    </div>
  );
};

export default BaseLayout;
