import Head from "next/head";
import { Inter } from "@next/font/google";
import BaseLayout from "../layouts";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <BaseLayout>
        <Head>
          <title>Next js beginner App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>next jS beginner app</h1>
      </BaseLayout>
    </>
  );
}
